name: macOS Test Environment

on:
  workflow_dispatch:

jobs:
  macos-test:
    runs-on: macos-13 # Use the latest available
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install package
        run: pip install -e .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
